baseURL = 'https://tomash.dog/'
locale = 'en-us'
title = "Tomash's Doghouse"
theme = 'maddybook'
disablePathToLower = true

[pagination]
    path = ""

[permalinks]
    post = '/:contentbasename/'

[params]
    copyright = "2026"
    home = "http://tomash.dog/"
    headline = "Writings of a dog-person on the the internet"
    customCSS = ['/css/doghouse.css']

[markup.goldmark.renderer]
    unsafe = true
