baseURL = 'https://tomash.dog/'
locale = 'en-us'
title = "Tomash's Doghouse"
theme = 'maddybook'
disablePathToLower = true

[pagination]
    path = ""

[permalinks]
    post = '/:contentbasename/'

[params]
    author = "Tomash"
    copyright = "[year unset]"
    home = "http://tomash.dog/"

[markup.goldmark.renderer]
    unsafe = true
